language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator_hexe_ruby_mongoid' ]; then cd .. && eval "mv $currentfolder generator_hexe_ruby_mongoid" && cd generator_hexe_ruby_mongoid; fi
