language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hexe-ruby-mongoid' ]; then cd .. && eval "mv $currentfolder generator-hexe-ruby-mongoid" && cd generator-hexe-ruby-mongoid; fi
